local-phone-apps = AxT9IME \
                   BackupRestoreConfirmation \
                   BadgeProvider \
                   Bluetooth \
                   BluetoothAvrcp \
                   BluetoothMap \
                   BluetoothTest \
                   CSC \
                   Camera \
                   ChocoEUKor \
                   ClipboardSaveService \
                   DataCreate \
                   DefaultContainerService \
                   Divx \
                   EdmVpnServices \
                   FaceLock \
                   FactoryTest \
                   FmRadio \
                   GoogleFeedback \
                   GoogleTTS \
                   HTMLViewer \
                   HelvNeueLT \
                   InputEventApp \
                   KeyChain \
                   LiveWallpapers \
                   LiveWallpapersPicker \
                   LogsProvider \
                   MarketUpdater \
                   MediaProvider \
                   MediaUploader \
                   MtpApplication \
                   MusicFX \
                   OmaCP \
                   PCWClientS \
                   PRUI \
                   PanningTryActually \
                   Personalization \
                   PhoneErrService \
                   Phone_Util \
                   Phonesky \
                   PopupuiReceiver \
                   Preconfig \
                   PreloadInstaller \
                   QuickView \
                   SamsungTTS \
                   SecBrowser \
                   SecOmaDownloadProvider \
                   SecPhone \
                   SecurityProvider \
                   SelfTestMode \
                   SerialNumberLabelIndicator \
                   ShareApp \
                   SharedStorageBackup \
                   Stk \
                   Street \
                   SurfSetProp \
                   UserDictionaryProvider \
                   VpnDialogs \
                   WAPPushManager \
                   WlanTest \
                   lcdtest \
                   minimode-res \
                   serviceModeApp \
                   shutdown \
                   wssyncmlnps \
                   ApplicationsProvider
